### ISSUE TITLE
Can't find a way to protect static resources.

### ISSUE THREAD

**Issue by eko234** [racket/web-server#101]
It seems to be no easy way to protect static resources with web servlets nor specific routes, I made my way to protect routes with higher order functions but i can't find a way to prevent the static files from being served to any request, maybe there is a way that I am not aware of, maybe there is a way to handle the file serving part or inserting some sort of "middleware" to run before the file dispatch...

I would appreciate your help, thanks in advance.

**Comment by jeapostrophe** [comment]
It depends on how you start the server. If you are using `serve/servlet`, then the only way is to have your servlet capture all requests by setting `servlet-regexp` to something like `""`. Another strategy would be to set the `extra-files-paths` to `empty`, so that it serves files, it just there aren't any.

`serve/servlet` is intended to be a quick way to get things going, but if you want something specific, you'd call `serve/launch/wait` and `dispatch/servlet` directly with your custom dispatcher chain. The source for it is intended to be easy-to-read and customizable. It's almost all setting up the contracts and defaults for the parameters --- https://github.com/racket/web-server/blob/master/web-server-lib/web-server/servlet-env.rkt

**Comment by eko234** [comment]
> 
> 
> It depends on how you start the server. If you are using `serve/servlet`, then the only way is to have your servlet capture all requests by setting `servlet-regexp` to something like `""`. Another strategy would be to set the `extra-files-paths` to `empty`, so that it serves files, it just there aren't any.
> 
> `serve/servlet` is intended to be a quick way to get things going, but if you want something specific, you'd call `serve/launch/wait` and `dispatch/servlet` directly with your custom dispatcher chain. The source for it is intended to be easy-to-read and customizable. It's almost all setting up the contracts and defaults for the parameters --- https://github.com/racket/web-server/blob/master/web-server-lib/web-server/servlet-env.rkt

sorry I was not clear enough, I was talking about allowing only certain requests to access static resources, like only if there is a auth header or something along those lines.

**Comment by jeapostrophe** [comment]
Ah, you would want to use this dispatcher https://docs.racket-lang.org/web-server-internal/dispatch-passwords.html in between lines 187 and 188 https://github.com/racket/web-server/blob/master/web-server-lib/web-server/servlet-env.rkt#L187-L188

**Comment by jeapostrophe** [comment]
You could also have your servlet grab everything and then use `(next-dispatcher)` for the ones that you want to pass down to files

**Comment by eko234** [comment]
thank you so much @jeapostrophe, now I know what I needed to know :p.
