### ISSUE TITLE
`web-server/http/request` lost `read-headers`

### ISSUE THREAD

**Issue by mflatt** [racket/web-server#80]
It looks like `read-headers` disappeared from the provides of `web-server/http/request` sometime since the branch for v7.5. That breaks the "rfc6455" package, at least.

**Comment by Bogdanp** [comment]
I un-provided `read-headers` and `parse-bindings` in https://github.com/racket/web-server/commit/c048b6f86d10d2af841e77d7e7e77232d8108dfc because they were not documented as part of the public interface so I thought they were only provided for testing purposes. I'll make a new PR to re-provide them.

@mflatt how did you notice the breakage? Did you run a local `pkg-build` or did you just happen to try to build the `rfc6455` package?

**Comment by mflatt** [comment]
I happened to install something that depends on `rfc6455`. Thanks for the repair!
